#!/usr/bin/env bash
set -euo pipefail

PYTHON_BIN="${PYTHON_BIN:-python3}"
RUN_ROOT="${RUN_ROOT:-runs/fineweb_high_lr_followup}"
LEARNING_RATES="${LEARNING_RATES:-5e-4 6e-4 7e-4 8e-4 9e-4 1e-3}"
MAX_ITERS="${MAX_ITERS:-1500}"
EVAL_INTERVAL="${EVAL_INTERVAL:-50}"
LOG_INTERVAL="${LOG_INTERVAL:-25}"
DATA_CHUNKS="${DATA_CHUNKS:-1}"
MODEL_KINDS="${MODEL_KINDS:-baseline hyperbolic}"
USE_MUON="${USE_MUON:-False}"
MUON_LR_RATIO="${MUON_LR_RATIO:-100}"
MUON_MOMENTUM="${MUON_MOMENTUM:-0.95}"
MUON_NESTEROV="${MUON_NESTEROV:-True}"
MUON_NS_STEPS="${MUON_NS_STEPS:-5}"

export PYTHON_BIN RUN_ROOT LEARNING_RATES MAX_ITERS EVAL_INTERVAL LOG_INTERVAL DATA_CHUNKS MODEL_KINDS
export USE_MUON MUON_LR_RATIO MUON_MOMENTUM MUON_NESTEROV MUON_NS_STEPS

./run_fineweb_lr_sweep.sh
"$PYTHON_BIN" plot_lr_sweep.py --run-root "$RUN_ROOT"
"$PYTHON_BIN" analyze_target_crossing.py --run-root "$RUN_ROOT"
